### ISSUE TITLE
syntax errors thrown by render & compile functions are hard to debug

### ISSUE THREAD

**Issue by stefan-guggisberg** [ForbesLindesay/QEJS#3]
syntax errors in generated code are hard to debug. if e.g. `qejs.compile(string, opts)` throws a `SyntaxError` it would help if the generated code that caused the error would be provided as a member of the error object.

see https://github.com/documentcloud/underscore/issues/666 for a related issue.

**Comment by ForbesLindesay** [comment]
True.  I'll accept pull requests that improve the situation.

**Comment by stefan-guggisberg** [comment]
thanks, i've created a pull request.
